/* Foundations: the subjects everything else leans on.
 *
 * Written with the type mix deliberate rather than incidental — a level that
 * is seven books is a reading list, and a path should hand you a lecture, a
 * thing to poke at and a repository to read as well.
 */

const CORE = [
  {
    slug: "algorithms",
    title: "Algorithms and data structures",
    topic: "algorithms",
    description:
      "Not interview drilling — the structures, the analysis, and why a good bound is worth more than a clever trick.",
    items: [
      { t: "MIT 6.006: Introduction to Algorithms", u: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/", k: "course", d: "beginner", s: "Lectures, problem sets and solutions. The standard first course, free in full." },
      { t: "VisuAlgo", u: "https://visualgo.net/en", k: "website", d: "beginner", s: "Every structure animated as it mutates. Ten minutes here beats an hour of pseudocode." },
      { t: "Algorithms by Jeff Erickson", u: "https://jeffe.cs.illinois.edu/teaching/algorithms/", k: "book", d: "beginner", s: "A free textbook that is genuinely enjoyable to read, which in this subject is rare." },
      { t: "Big-O cheat sheet", u: "https://www.bigocheatsheet.com/", k: "website", d: "beginner", s: "Every common structure and its bounds on one page. Worth pinning early." },
      { t: "Sorting algorithms visualised", u: "https://www.toptal.com/developers/sorting-algorithms", k: "website", d: "beginner", s: "The same input sorted six ways side by side, including where each one falls apart." },
      { t: "Khan Academy: Algorithms", u: "https://www.khanacademy.org/computing/computer-science/algorithms", k: "course", d: "beginner", s: "Built with Dartmouth. The gentlest complete introduction, with runnable challenges." },
      { t: "The Algorithms", u: "https://github.com/TheAlgorithms/Python", k: "code", d: "beginner", s: "Readable reference implementations in one repo, to check yourself against." },
      { t: "Princeton: Algorithms", u: "https://algs4.cs.princeton.edu/home/", k: "course", d: "intermediate", s: "Sedgewick's course site, with the code, the exercises and the empirical analysis." },
      { t: "MIT 6.046: Design and Analysis", u: "https://ocw.mit.edu/courses/6-046j-design-and-analysis-of-algorithms-spring-2015/", k: "course", d: "intermediate", s: "Amortised analysis, randomised algorithms and the start of NP-completeness." },
      { t: "Amortized analysis", u: "https://jeffe.cs.illinois.edu/teaching/algorithms/book/Algorithms-JeffE.pdf", k: "book", d: "intermediate", s: "The whole of Erickson as one PDF — amortised analysis in chapter 6 is the highlight." },
      { t: "Competitive Programmer's Handbook", u: "https://cses.fi/book/book.pdf", k: "book", d: "intermediate", s: "Laaksonen's free book. The most efficient tour of techniques that actually recur." },
      { t: "CSES Problem Set", u: "https://cses.fi/problemset/", k: "course", d: "intermediate", s: "Three hundred problems ordered by technique, each with a real judge behind it." },
      { t: "Red-black trees, explained", u: "https://www.cs.usfca.edu/~galles/visualization/RedBlack.html", k: "website", d: "intermediate", s: "Insert and delete step by step, watching the rebalance happen." },
      { t: "Python's list and dict internals", u: "https://github.com/python/cpython/blob/main/Objects/listobject.c", k: "code", d: "intermediate", s: "The growth strategy behind a language's most-used structure, in the source." },
      { t: "Introduction to Theoretical Computer Science", u: "https://introtcs.org/public/index.html", k: "book", d: "advanced", s: "Barak's Harvard text. Computability and complexity from first principles." },
      { t: "Computational Complexity: A Modern Approach", u: "https://theory.cs.princeton.edu/complexity/book.pdf", k: "book", d: "advanced", s: "Arora and Barak's draft. The reference for what is hard and why." },
      { t: "Approximation algorithms", u: "https://www.designofapproxalgs.com/", k: "book", d: "advanced", s: "Williamson and Shmoys, free. What to do when the exact answer is out of reach." },
      { t: "Randomized algorithms lecture notes", u: "https://www.cs.cmu.edu/~15859n/", k: "course", d: "advanced", s: "CMU's course. Concentration bounds and why randomness so often beats cleverness." },
      { t: "A Fast Quantum Mechanical Algorithm for Database Search", u: "https://arxiv.org/abs/quant-ph/9605043", k: "paper", d: "advanced", s: "Grover's paper — the clearest example of a genuinely different model of computation." },
      { t: "Papers We Love: algorithms", u: "https://github.com/papers-we-love/papers-we-love", k: "code", d: "advanced", s: "The canon, collected. Where to go once the textbooks stop being the frontier." },
      { t: "Open Data Structures", u: "https://opendatastructures.org/", k: "book", d: "advanced", s: "Pat Morin's free text, with every structure proved rather than asserted." },
    ],
  },
  {
    slug: "operating-systems",
    title: "How an operating system works",
    topic: "operating systems",
    description:
      "Processes, memory, files and the scheduler — the layer every program you write is standing on.",
    items: [
      { t: "Operating Systems: Three Easy Pieces", u: "https://pages.cs.wisc.edu/~remzi/OSTEP/", k: "book", d: "beginner", s: "Free, complete, and the clearest OS book written. Virtualisation, concurrency, persistence." },
      { t: "MIT 6.1810: Operating System Engineering", u: "https://pdos.csail.mit.edu/6.828/2023/schedule.html", k: "course", d: "beginner", s: "Build a Unix-like kernel. Labs, xv6 source and every lecture, public." },
      { t: "The Missing Semester", u: "https://missing.csail.mit.edu/", k: "course", d: "beginner", s: "Shell, processes and job control — the OS surface you actually touch daily." },
      { t: "Linux man pages", u: "https://man7.org/linux/man-pages/", k: "website", d: "beginner", s: "The system call interface, documented precisely. Section 2 is the OS proper." },
      { t: "Let's Write a Kernel", u: "https://os.phil-opp.com/", k: "article", d: "beginner", s: "Philipp Oppermann building an OS in Rust, one readable post at a time." },
      { t: "xv6 source", u: "https://github.com/mit-pdos/xv6-riscv", k: "code", d: "beginner", s: "A complete teaching kernel small enough to read end to end in a weekend." },
      { t: "How does a Linux boot work", u: "https://github.com/0xAX/linux-insides", k: "code", d: "beginner", s: "Linux internals written as a book, starting from the first instruction executed." },
      { t: "Concurrency: OSTEP chapters", u: "https://pages.cs.wisc.edu/~remzi/OSTEP/threads-intro.pdf", k: "book", d: "intermediate", s: "Threads, locks and condition variables, built up from what the hardware guarantees." },
      { t: "What every programmer should know about memory", u: "https://people.freebsd.org/~lstewart/articles/cpumemory.pdf", k: "paper", d: "intermediate", s: "Drepper's 114 pages on caches and DRAM. Still the reference two decades on." },
      { t: "Linux Performance", u: "https://www.brendangregg.com/linuxperf.html", k: "website", d: "intermediate", s: "Brendan Gregg's map of every tool and the layer it observes." },
      { t: "The Linux Kernel documentation", u: "https://docs.kernel.org/", k: "website", d: "intermediate", s: "Scheduler, memory management and filesystems, from the people maintaining them." },
      { t: "Operating Systems lecture series", u: "https://www.youtube.com/playlist?list=PLBlnK6fEyqRiVhbXDGLXDk_OQAeuVcp2O", k: "video", d: "intermediate", s: "Neso Academy's full course, useful when the book's prose isn't landing." },
      { t: "Advanced Programming in the UNIX Environment — sample", u: "https://stevens.netmeister.org/631/", k: "course", d: "intermediate", s: "Stevens' material taught as a systems course, with every assignment public." },
      { t: "strace, ltrace and friends", u: "https://jvns.ca/blog/2015/04/14/strace-zine/", k: "article", d: "intermediate", s: "Julia Evans on watching a process talk to the kernel, which is how you debug it." },
      { t: "The Linux kernel source", u: "https://github.com/torvalds/linux", k: "code", d: "advanced", s: "kernel/sched/ and mm/ are where the ideas in every OS textbook actually live." },
      { t: "The Design and Implementation of a Log-Structured File System", u: "https://web.stanford.edu/~ouster/cgi-bin/papers/lfs.pdf", k: "paper", d: "advanced", s: "Rosenblum and Ousterhout. The idea under every modern SSD-aware filesystem." },
      { t: "The UNIX Time-Sharing System", u: "https://dsf.berkeley.edu/cs262/unix.pdf", k: "paper", d: "advanced", s: "Ritchie and Thompson, 1974. Eleven pages that set the shape of everything after." },
      { t: "Scheduling: the Completely Fair Scheduler", u: "https://docs.kernel.org/scheduler/sched-design-CFS.html", k: "website", d: "advanced", s: "How Linux decides what runs next, documented by the people who wrote it." },
      { t: "CMU 15-213: Computer Systems", u: "https://www.cs.cmu.edu/~213/", k: "course", d: "advanced", s: "Page tables, TLBs and what a fault actually costs, with the labs that prove it." },
      { t: "seL4: Formal Verification of an OS Kernel", u: "https://sigops.org/s/conferences/sosp/2009/papers/klein-sosp09.pdf", k: "paper", d: "advanced", s: "A kernel proved correct. The strongest claim anyone has made about systems software." },
      { t: "Writing an OS in Rust — source", u: "https://github.com/phil-opp/blog_os", k: "code", d: "advanced", s: "The full repository behind the blog series, tagged post by post." },
    ],
  },
  {
    slug: "networking",
    title: "How the internet actually works",
    topic: "computer networking",
    description:
      "From a socket to BGP — what happens between typing a URL and the bytes arriving.",
    items: [
      { t: "Computer Networking: A Top-Down Approach", u: "https://gaia.cs.umass.edu/kurose_ross/index.php", k: "book", d: "beginner", s: "The standard text, with the authors' own interactive material and Wireshark labs." },
      { t: "How DNS works", u: "https://howdns.works/", k: "website", d: "beginner", s: "A comic that explains resolution better than most chapters do." },
      { t: "High Performance Browser Networking", u: "https://hpbn.co/", k: "book", d: "beginner", s: "Grigorik's book, free in full. TCP, TLS and HTTP from the browser's point of view." },
      { t: "What happens when you type a URL", u: "https://github.com/alex/what-happens-when", k: "code", d: "beginner", s: "The whole stack, one step at a time, maintained as a repository." },
      { t: "Stanford CS144: Introduction to Computer Networking", u: "https://stanford.edu/class/cs144/", k: "course", d: "beginner", s: "Build a working TCP implementation. Lectures and labs entirely public." },
      { t: "MDN: HTTP", u: "https://developer.mozilla.org/en-US/docs/Web/HTTP", k: "website", d: "beginner", s: "Methods, headers, status codes and caching — the protocol you use most." },
      { t: "Julia Evans: networking zines", u: "https://jvns.ca/categories/networking/", k: "article", d: "beginner", s: "Short, concrete explanations of the parts that usually stay mysterious." },
      { t: "TLS 1.3 — every byte explained", u: "https://tls13.xargs.org/", k: "website", d: "intermediate", s: "An annotated handshake, byte by byte. Nothing else makes TLS this concrete." },
      { t: "Wireshark", u: "https://www.wireshark.org/docs/wsug_html_chunked/", k: "course", d: "intermediate", s: "The user guide. Reading your own traffic is the fastest way to learn a protocol." },
      { t: "Beej's Guide to Network Programming", u: "https://beej.us/guide/bgnet/", k: "book", d: "intermediate", s: "Sockets in C, explained by someone who wants you to succeed. Free for 25 years." },
      { t: "HTTP/2 and HTTP/3 explained", u: "https://http3-explained.haxx.se/", k: "book", d: "intermediate", s: "Daniel Stenberg on what changed and why, from the author of curl." },
      { t: "Cloudflare Learning Center", u: "https://www.cloudflare.com/learning/", k: "website", d: "intermediate", s: "CDNs, DDoS, BGP and DNS, written for engineers rather than buyers." },
      { t: "The curl source", u: "https://github.com/curl/curl", k: "code", d: "intermediate", s: "Twenty-five years of protocol edge cases, all of them commented." },
      { t: "Network Programming lectures", u: "https://www.youtube.com/playlist?list=PLoCMsyE1cvdWKsLVyf6cPwCLDIZnOj0NS", k: "video", d: "intermediate", s: "A full socket-programming series, useful alongside Beej." },
      { t: "RFC 9110: HTTP Semantics", u: "https://www.rfc-editor.org/rfc/rfc9110.html", k: "paper", d: "advanced", s: "The specification itself. Shorter and clearer than its reputation suggests." },
      { t: "RFC 9000: QUIC", u: "https://www.rfc-editor.org/rfc/rfc9000.html", k: "paper", d: "advanced", s: "The transport under HTTP/3, and the first real replacement for TCP in decades." },
      { t: "APNIC: tech matters", u: "https://blog.apnic.net/category/tech-matters/", k: "website", d: "advanced", s: "Geoff Huston and colleagues on routing, DNS and the table the internet depends on." },
      { t: "Congestion Avoidance and Control", u: "https://ee.lbl.gov/papers/congavoid.pdf", k: "paper", d: "advanced", s: "Jacobson and Karels, 1988. The paper that stopped the internet collapsing." },
      { t: "BBR: Congestion-Based Congestion Control", u: "https://research.google/pubs/bbr-congestion-based-congestion-control/", k: "paper", d: "advanced", s: "Google's replacement for loss-based control, and why the old model stopped fitting." },
      { t: "The QUIC reference implementation", u: "https://github.com/quicwg/base-drafts", k: "code", d: "advanced", s: "The working group's own repository, with every design argument in the issues." },
      { t: "Cloudflare blog: protocols", u: "https://blog.cloudflare.com/tag/protocols/", k: "website", d: "advanced", s: "Deep post-mortems and protocol work from people operating at internet scale." },
    ],
  },
  {
    slug: "statistics",
    title: "Statistics you can trust",
    topic: "statistics",
    description:
      "Estimation, inference and uncertainty — including why so much published work does not replicate.",
    items: [
      { t: "Seeing Theory", u: "https://seeing-theory.brown.edu/", k: "website", d: "beginner", s: "Brown's visual introduction. Drag the parameters and watch the distribution move." },
      { t: "StatQuest", u: "https://www.youtube.com/@statquest", k: "video", d: "beginner", s: "Josh Starmer explaining each idea twice — once with pictures, once with the maths." },
      { t: "OpenIntro Statistics", u: "https://www.openintro.org/book/os/", k: "book", d: "beginner", s: "A full first course, free as a PDF, with data and labs alongside." },
      { t: "Think Stats", u: "https://allendowney.github.io/ThinkStats/", k: "book", d: "beginner", s: "Downey's book for programmers: every concept arrives as code you can run." },
      { t: "Khan Academy: Statistics and probability", u: "https://www.khanacademy.org/math/statistics-probability", k: "course", d: "beginner", s: "Exercise-driven and thorough, for filling gaps rather than reading front to back." },
      { t: "Common statistical tests are linear models", u: "https://lindeloev.github.io/tests-as-linear/", k: "article", d: "beginner", s: "The single insight that collapses a semester of named tests into one idea." },
      { t: "Spurious Correlations", u: "https://www.tylervigen.com/spurious-correlations", k: "website", d: "beginner", s: "Correlation and causation, made unforgettable by absurdity." },
      { t: "An Introduction to Statistical Learning", u: "https://www.statlearning.com/", k: "book", d: "intermediate", s: "ISLR, free from the authors, with labs in both R and Python." },
      { t: "Statistical Rethinking lectures", u: "https://www.youtube.com/playlist?list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus", k: "video", d: "intermediate", s: "McElreath's course. The best available teaching of Bayesian inference." },
      { t: "Regression and Other Stories", u: "https://avehtari.github.io/ROS-Examples/", k: "code", d: "intermediate", s: "Gelman's book's full worked examples and data, free and runnable." },
      { t: "Regression and Other Stories", u: "https://users.aalto.fi/~ave/ROS.pdf", k: "book", d: "intermediate", s: "Gelman, Hill and Vehtari on regression and multilevel models. Free, and the best modern treatment." },
      { t: "The ASA statement on p-values", u: "https://www.amstat.org/asa/files/pdfs/p-valuestatement.pdf", k: "paper", d: "intermediate", s: "The profession's own correction on the most misused number in science." },
      { t: "Statistical Modeling, Causal Inference and Social Science", u: "https://statmodeling.stat.columbia.edu/", k: "website", d: "intermediate", s: "Gelman's blog. Twenty years of working through real analyses in public." },
      { t: "Bayesian Methods for Hackers", u: "https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers", k: "code", d: "intermediate", s: "A whole book as notebooks, computation first and theory when you need it." },
      { t: "Why Most Published Research Findings Are False", u: "https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.0020124", k: "paper", d: "advanced", s: "Ioannidis, 2005. The paper that started the replication crisis, and it is readable." },
      { t: "Bayesian Data Analysis", u: "http://www.stat.columbia.edu/~gelman/book/", k: "book", d: "advanced", s: "BDA3, free as a PDF from Gelman. The standard graduate reference." },
      { t: "Causal Inference: What If", u: "https://miguelhernan.org/whatifbook", k: "book", d: "advanced", s: "Hernán and Robins, free. Causal inference done carefully rather than by slogan." },
      { t: "Stan", u: "https://github.com/stan-dev/stan", k: "code", d: "advanced", s: "The sampler most modern Bayesian work runs on, and its documentation is a course." },
      { t: "The Garden of Forking Paths", u: "http://www.stat.columbia.edu/~gelman/research/unpublished/forking.pdf", k: "paper", d: "advanced", s: "Why a result can be p-hacked without anyone intending to hack anything." },
      { t: "Visualization in Bayesian workflow", u: "https://arxiv.org/abs/1709.01449", k: "paper", d: "advanced", s: "Gabry et al. on checking a model rather than trusting it." },
      { t: "Cross Validated", u: "https://stats.stackexchange.com/", k: "website", d: "advanced", s: "The one Q&A site where statistical answers are routinely better than textbooks." },
    ],
  },
  {
    slug: "linear-algebra",
    title: "Linear algebra, intuitively",
    topic: "linear algebra",
    description:
      "Vectors, transformations and eigenvalues — the mathematics under graphics, statistics and every neural network.",
    items: [
      { t: "Essence of Linear Algebra", u: "https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab", k: "video", d: "beginner", s: "3Blue1Brown. The series that makes determinants and eigenvectors mean something." },
      { t: "Immersive Linear Algebra", u: "http://immersivemath.com/ila/index.html", k: "book", d: "beginner", s: "The first book with fully interactive figures. Drag the vectors and the maths follows." },
      { t: "MIT 18.06 with Gilbert Strang", u: "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/", k: "course", d: "beginner", s: "The most loved mathematics course on the internet, complete with exams." },
      { t: "Introduction to Linear Algebra — resources", u: "https://math.mit.edu/~gs/linearalgebra/", k: "website", d: "beginner", s: "Strang's own page: lecture tables, problem sets and the book's supporting material." },
      { t: "Interactive Linear Algebra", u: "https://textbooks.math.gatech.edu/ila/", k: "book", d: "beginner", s: "Georgia Tech's free text, with every example manipulable in the page." },
      { t: "Matrix multiplication, visualised", u: "http://matrixmultiplication.xyz/", k: "website", d: "beginner", s: "One animation that fixes the operation in your head permanently." },
      { t: "NumPy: linear algebra", u: "https://numpy.org/doc/stable/reference/routines.linalg.html", k: "website", d: "beginner", s: "The routines you will actually call, and what each one assumes about your matrix." },
      { t: "Linear Algebra Done Right", u: "https://linear.axler.net/", k: "book", d: "intermediate", s: "Axler, free from the author. Builds the theory without leaning on determinants." },
      { t: "The Matrix Cookbook", u: "https://www.math.uwaterloo.ca/~hwolkowi/matrixcookbook.pdf", k: "paper", d: "intermediate", s: "Every identity and derivative you will need, on tap. Not for reading front to back." },
      { t: "Computational Linear Algebra", u: "https://github.com/fastai/numerical-linear-algebra", k: "code", d: "intermediate", s: "fast.ai's course as notebooks: decompositions applied to real problems." },
      { t: "Mathematics for Machine Learning", u: "https://mml-book.github.io/", k: "book", d: "intermediate", s: "Deisenroth et al., free. The linear algebra actually used downstream, and only that." },
      { t: "Singular Value Decomposition, explained", u: "https://gregorygundersen.com/blog/2018/12/10/svd/", k: "article", d: "intermediate", s: "The decomposition that quietly powers compression, recommendation and PCA." },
      { t: "MIT 18.065: Matrix Methods", u: "https://ocw.mit.edu/courses/18-065-matrix-methods-in-data-analysis-signal-processing-and-machine-learning-spring-2018/", k: "course", d: "intermediate", s: "Strang again, aimed squarely at data. The sequel worth taking." },
      { t: "Eigenvectors and eigenvalues", u: "https://setosa.io/ev/eigenvectors-and-eigenvalues/", k: "website", d: "intermediate", s: "Explained visually, with the transformation under your cursor." },
      { t: "Numerical Linear Algebra", u: "https://people.maths.ox.ac.uk/trefethen/text.html", k: "book", d: "advanced", s: "Trefethen and Bau. What happens to the clean theory in floating point." },
      { t: "Randomized numerical linear algebra", u: "https://arxiv.org/abs/2002.01387", k: "paper", d: "advanced", s: "How the very large matrices are handled: sample first, decompose second." },
      { t: "LAPACK", u: "https://github.com/Reference-LAPACK/lapack", k: "code", d: "advanced", s: "Fortran that almost every numerical stack still calls into. Worth reading once." },
      { t: "Finding Structure with Randomness", u: "https://arxiv.org/abs/0909.4061", k: "paper", d: "advanced", s: "Halko, Martinsson and Tropp — the randomised SVD that changed large-scale practice." },
      { t: "Convex Optimization", u: "https://web.stanford.edu/~boyd/cvxbook/", k: "book", d: "advanced", s: "Boyd and Vandenberghe, free from Stanford. Where the linear algebra is going." },
      { t: "Tensor methods, a survey", u: "https://arxiv.org/abs/1711.10781", k: "paper", d: "advanced", s: "What happens when a matrix is not enough and the data has more than two axes." },
      { t: "The Art of Linear Algebra", u: "https://github.com/kenjihiranabe/The-Art-of-Linear-Algebra", k: "code", d: "advanced", s: "Strang's key results as one-page graphic notes. Excellent for consolidation." },
    ],
  },
  {
    slug: "cryptography",
    title: "Cryptography and how it fails",
    topic: "cryptography",
    description:
      "The primitives, the protocols built on them, and the long history of them being used wrongly.",
    items: [
      { t: "Cryptopals Crypto Challenges", u: "https://cryptopals.com/", k: "course", d: "beginner", s: "Break real ciphers yourself, in order. Nothing else teaches this as fast." },
      { t: "Crypto 101", u: "https://www.crypto101.io/", k: "book", d: "beginner", s: "A free introductory book for programmers, assuming no mathematics up front." },
      { t: "Computerphile: cryptography", u: "https://www.youtube.com/playlist?list=PLzH6n4zXuckpoaxDKOOV26yhgoY2S-xYg", k: "video", d: "beginner", s: "Short explanations of each primitive with people who work on them." },
      { t: "TLS 1.3 — every byte explained", u: "https://tls13.xargs.org/", k: "website", d: "beginner", s: "An annotated handshake. The best way to see the primitives in combination." },
      { t: "Stanford CS255: Introduction to Cryptography", u: "https://crypto.stanford.edu/~dabo/courses/OnlineCrypto/", k: "course", d: "beginner", s: "Dan Boneh's course notes and problem sets, free." },
      { t: "Cryptographic Right Answers", u: "https://www.latacora.com/blog/2018/04/03/cryptographic-right-answers/", k: "article", d: "beginner", s: "What to actually use, per task, from people who audit this for a living." },
      { t: "libsodium documentation", u: "https://doc.libsodium.org/", k: "website", d: "beginner", s: "The library designed so the dangerous choices are not available to make." },
      { t: "A Graduate Course in Applied Cryptography", u: "https://toc.cryptobook.us/", k: "book", d: "intermediate", s: "Boneh and Shoup, free. The standard modern treatment, proofs included." },
      { t: "The Joy of Cryptography", u: "https://joyofcryptography.com/", k: "book", d: "intermediate", s: "Rosulek's free textbook, built around security definitions rather than recipes." },
      { t: "Real World Crypto talks", u: "https://www.youtube.com/@RealWorldCrypto", k: "video", d: "intermediate", s: "The conference where deployed cryptography gets examined in public." },
      { t: "How to Safely Use Hash Functions", u: "https://csrc.nist.gov/projects/hash-functions", k: "website", d: "intermediate", s: "NIST's own pages on what is approved, deprecated and broken." },
      { t: "Elliptic Curve Cryptography, a gentle introduction", u: "https://andrea.corbellini.name/2015/05/17/elliptic-curve-cryptography-a-gentle-introduction/", k: "article", d: "intermediate", s: "The four-part series that makes ECC click without a maths degree." },
      { t: "The Tink library", u: "https://github.com/tink-crypto/tink", k: "code", d: "intermediate", s: "Google's misuse-resistant API. Reading it teaches what the footguns were." },
      { t: "Password hashing: the state of play", u: "https://www.rfc-editor.org/rfc/rfc9106.html", k: "paper", d: "intermediate", s: "The Argon2 RFC, and the reasoning behind the parameters everyone gets wrong." },
      { t: "New Directions in Cryptography", u: "https://ee.stanford.edu/~hellman/publications/24.pdf", k: "paper", d: "advanced", s: "Diffie and Hellman, 1976. Public-key cryptography, proposed for the first time." },
      { t: "A Method for Obtaining Digital Signatures", u: "https://people.csail.mit.edu/rivest/Rsapaper.pdf", k: "paper", d: "advanced", s: "The RSA paper. Still the clearest statement of the construction." },
      { t: "Post-Quantum Cryptography standards", u: "https://csrc.nist.gov/projects/post-quantum-cryptography", k: "website", d: "advanced", s: "The algorithms selected to replace RSA and ECC, with the full evaluation record." },
      { t: "Logjam: Imperfect Forward Secrecy", u: "https://weakdh.org/", k: "website", d: "advanced", s: "How a decades-old export restriction broke real TLS in 2015, with the paper and the test." },
      { t: "The Ristretto group", u: "https://ristretto.group/", k: "website", d: "advanced", s: "A worked example of designing an abstraction so a whole bug class disappears." },
      { t: "BearSSL source", u: "https://www.bearssl.org/gitweb/?p=BearSSL;a=summary", k: "code", d: "advanced", s: "A TLS stack written to be auditable, with the reasoning documented throughout." },
      { t: "Cryptocoding", u: "https://github.com/veorq/cryptocoding", k: "code", d: "advanced", s: "Aumasson's rules for writing crypto that does not leak through timing or branches." },
    ],
  },
  {
    slug: "writing-well",
    title: "Writing well",
    topic: "writing",
    description:
      "Clarity, structure and revision — treated as a craft with rules rather than a talent you have or don't.",
    items: [
      { t: "The Elements of Style", u: "https://www.gutenberg.org/ebooks/37134", k: "book", d: "beginner", s: "Strunk, free from Gutenberg. Dated in places, still the fastest hour you can spend." },
      { t: "Politics and the English Language", u: "https://www.orwell.ru/library/essays/politics/english/e_polit", k: "article", d: "beginner", s: "Orwell's six rules, and the argument for why vague writing is not harmless." },
      { t: "Hemingway Editor", u: "https://hemingwayapp.com/", k: "website", d: "beginner", s: "Paste a draft and watch your worst sentences light up. Blunt and useful." },
      { t: "On Writing Well — Zinsser's lecture", u: "https://www.youtube.com/watch?v=ZWLFtHTaFtY", k: "video", d: "beginner", s: "Zinsser at Yale on simplicity and clutter, which is the whole book in an hour." },
      { t: "Purdue OWL", u: "https://owl.purdue.edu/owl/purdue_owl.html", k: "website", d: "beginner", s: "The reference for grammar, citation and mechanics, and it is genuinely complete." },
      { t: "Writing Well — a practical guide", u: "https://www.julian.com/guide/write/intro", k: "course", d: "beginner", s: "Julian Shapiro's free course, aimed at people writing on the internet." },
      { t: "Paul Graham's essays", u: "https://paulgraham.com/articles.html", k: "website", d: "beginner", s: "Worth reading as much for the sentence construction as the arguments." },
      { t: "Style: Lessons in Clarity and Grace — notes", u: "https://www.cs.cmu.edu/~jrs/sins.html", k: "article", d: "intermediate", s: "Williams' method reduced to a checklist: subjects as actors, verbs as actions." },
      { t: "The Science of Scientific Writing", u: "https://www.americanscientist.org/blog/the-long-view/the-science-of-scientific-writing", k: "article", d: "intermediate", s: "Gopen and Swan on reader expectation. Changes how you order a sentence." },
      { t: "Steven Pinker on writing", u: "https://www.youtube.com/watch?v=OV5J6BfToSw", k: "video", d: "intermediate", s: "The classic-style argument: prose as a window, not a performance." },
      { t: "Draft No. 4", u: "https://www.newyorker.com/magazine/2013/04/29/draft-no-4", k: "article", d: "intermediate", s: "John McPhee on revision — the part of writing that actually produces the quality." },
      { t: "Google Technical Writing Courses", u: "https://developers.google.com/tech-writing", k: "course", d: "intermediate", s: "Two free courses with exercises, aimed at engineers who have to write." },
      { t: "The Elements of Eloquence — Forsyth on rhetoric", u: "https://www.gutenberg.org/ebooks/45109", k: "book", d: "intermediate", s: "Genung's working rhetoric: the figures that make a sentence land, catalogued." },
      { t: "Write the Docs", u: "https://www.writethedocs.org/guide/", k: "website", d: "intermediate", s: "The documentation community's collected guidance on structure and maintenance." },
      { t: "The Sense of Style — talk", u: "https://www.youtube.com/watch?v=3ZKTmsgqi0U", k: "video", d: "advanced", s: "Pinker on why good writers write badly, and the curse of knowledge behind it." },
      { t: "London Review of Books", u: "https://www.lrb.co.uk/", k: "website", d: "advanced", s: "Long-form criticism worth reading as a model for argument at length." },
      { t: "Nature: writing for a broad audience", u: "https://www.nature.com/articles/d41586-019-02918-5", k: "article", d: "advanced", s: "How specialists lose readers, and the specific habits that cause it." },
      { t: "Rhetoric — Aristotle", u: "https://classics.mit.edu/Aristotle/rhetoric.html", k: "book", d: "advanced", s: "The original analysis of persuasion, and still the most systematic." },
      { t: "Chicago Manual of Style Online — Q&A", u: "https://www.chicagomanualofstyle.org/qanda/latest.html", k: "website", d: "advanced", s: "Hard cases argued by editors. The free half, and the interesting half." },
      { t: "Style guide for technical prose", u: "https://github.com/google/styleguide", k: "code", d: "advanced", s: "Google's guides as a repository, with the arguments recorded in the history." },
      { t: "Vonnegut on the shapes of stories", u: "https://www.youtube.com/watch?v=oP3c1h8v2ZQ", k: "video", d: "advanced", s: "Structure reduced to a chalkboard diagram. Applies well beyond fiction." },
    ],
  },
];

module.exports = { CORE };
