/* Computer science and systems.
 *
 * The one area where the best free material genuinely beats the paid kind:
 * MIT, Berkeley and CMU publish whole courses, and the canonical database and
 * distributed-systems papers were never behind a paywall to begin with.
 */

const CS = [
  {
    slug: "computer-science",
    title: "A computer science education",
    topic: "computer science",
    description:
      "The degree, assembled from the courses universities put online — abstraction, algorithms, machines and theory, in an order that builds.",
    items: [
      { t: "CS50x: Introduction to Computer Science", u: "https://cs50.harvard.edu/x/", k: "course", d: "beginner", s: "Harvard's introduction, and the best-produced course in the subject. C first, deliberately." },
      { t: "Structure and Interpretation of Computer Programs", u: "https://web.mit.edu/6.001/6.037/sicp.pdf", k: "book", d: "beginner", s: "SICP. The book about what programs mean rather than how to write them." },
      { t: "The Missing Semester of Your CS Education", u: "https://missing.csail.mit.edu/", k: "course", d: "beginner", s: "Shell, git, editors and debugging — the tooling every course assumes and none teach." },
      { t: "Teach Yourself Computer Science", u: "https://teachyourselfcs.com/", k: "website", d: "beginner", s: "Nine subjects, one book and one course each, with an argument for every choice." },
      { t: "Crash Course Computer Science", u: "https://www.youtube.com/playlist?list=PL8dPuuaLjXtNlUrzyH5r6jN9ulIgZBpdo", k: "video", d: "beginner", s: "Forty episodes from relays to machine learning. The map before the territory." },
      { t: "Nand2Tetris", u: "https://www.nand2tetris.org/", k: "course", d: "beginner", s: "Build a computer from a NAND gate up to an operating system. Nothing else replaces it." },
      { t: "Python for Everybody", u: "https://www.py4e.com/", k: "course", d: "beginner", s: "If you need a language first, this is the gentlest complete one that is free." },
      { t: "Computer Systems: A Programmer's Perspective — course", u: "https://www.cs.cmu.edu/~213/", k: "course", d: "intermediate", s: "CMU's 15-213. The course that turns a programmer into someone who knows what runs." },
      { t: "MIT 6.006: Introduction to Algorithms", u: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/", k: "course", d: "intermediate", s: "Full lectures, problem sets and solutions. The standard algorithms course, free." },
      { t: "Algorithms by Jeff Erickson", u: "https://jeffe.cs.illinois.edu/teaching/algorithms/", k: "book", d: "intermediate", s: "A free algorithms textbook that is genuinely enjoyable to read, which is rare." },
      { t: "Operating Systems: Three Easy Pieces", u: "https://pages.cs.wisc.edu/~remzi/OSTEP/", k: "book", d: "intermediate", s: "Virtualisation, concurrency, persistence. Free, complete, and the clearest OS book there is." },
      { t: "Computer Networking: A Top-Down Approach", u: "https://gaia.cs.umass.edu/kurose_ross/index.php", k: "book", d: "intermediate", s: "The standard networking text, with the authors' own interactive material alongside." },
      { t: "Crafting Interpreters", u: "https://craftinginterpreters.com/", k: "book", d: "intermediate", s: "Two complete interpreters, built line by line. Free in full and beautifully made." },
      { t: "Berkeley CS61A: Structure and Interpretation", u: "https://cs61a.org/", k: "course", d: "intermediate", s: "SICP's ideas in Python, with every lecture, lab and exam public." },
      { t: "Introduction to Theoretical Computer Science", u: "https://introtcs.org/public/index.html", k: "book", d: "advanced", s: "Boaz Barak's Harvard text. Computability and complexity from first principles." },
      { t: "MIT 6.046: Design and Analysis of Algorithms", u: "https://ocw.mit.edu/courses/6-046j-design-and-analysis-of-algorithms-spring-2015/", k: "course", d: "advanced", s: "The advanced course — amortised analysis, randomised algorithms, NP-completeness." },
      { t: "Computational Complexity: A Modern Approach", u: "https://theory.cs.princeton.edu/complexity/book.pdf", k: "book", d: "advanced", s: "Arora and Barak's draft, free. The reference for what is hard and why." },
      { t: "Types and Programming Languages — course notes", u: "https://www.cis.upenn.edu/~bcpierce/sf/current/index.html", k: "book", d: "advanced", s: "Software Foundations: type theory and proof, machine-checked in Coq as you read." },
      { t: "The Art of Computer Programming — errata and notes", u: "https://www-cs-faculty.stanford.edu/~knuth/taocp.html", k: "website", d: "advanced", s: "Knuth's own page for the series, with the free fascicle drafts he keeps posting." },
      { t: "Distributed Systems (Cambridge) lecture notes", u: "https://www.cl.cam.ac.uk/teaching/2122/ConcDisSys/dist-sys-notes.pdf", k: "book", d: "advanced", s: "Martin Kleppmann's notes. Consensus and consistency in 80 careful pages." },
      { t: "Papers We Love", u: "https://github.com/papers-we-love/papers-we-love", k: "code", d: "advanced", s: "The canon, organised by subject. Where to go once textbooks stop being the frontier." },
    ],
  },
  {
    slug: "databases",
    title: "Databases, from query to disk",
    topic: "databases",
    description:
      "What actually happens between typing SELECT and the bytes coming back — indexes, transactions, storage engines and the papers underneath.",
    items: [
      { t: "SQLBolt", u: "https://sqlbolt.com/", k: "course", d: "beginner", s: "SQL taught as exercises against a live database in the page. No setup at all." },
      { t: "Select Star SQL", u: "https://selectstarsql.com/", k: "book", d: "beginner", s: "A free interactive book that teaches SQL through one real dataset worth thinking about." },
      { t: "PostgreSQL Tutorial", u: "https://www.postgresql.org/docs/current/tutorial.html", k: "website", d: "beginner", s: "The official introduction. Short, and it covers the parts other tutorials skip." },
      { t: "Use The Index, Luke", u: "https://use-the-index-luke.com/", k: "book", d: "beginner", s: "Indexing explained for developers rather than DBAs. The highest-value database reading there is." },
      { t: "SQLZoo", u: "https://sqlzoo.net/wiki/SQL_Tutorial", k: "course", d: "beginner", s: "Graded exercises from SELECT to window functions, marked in the browser as you go." },
      { t: "Database normalisation, explained", u: "https://www.postgresql.org/docs/current/ddl-constraints.html", k: "website", d: "beginner", s: "Constraints as the database enforcing your invariants instead of your application forgetting them." },
      { t: "SQL Murder Mystery", u: "https://mystery.knightlab.com/", k: "course", d: "beginner", s: "Learn joins by solving a crime. Genuinely the fastest way to make queries stick." },
      { t: "CMU 15-445: Intro to Database Systems", u: "https://15445.courses.cs.cmu.edu/", k: "course", d: "intermediate", s: "Andy Pavlo's course, all lectures public. The best database teaching available anywhere." },
      { t: "Postgres: Indexes", u: "https://www.postgresql.org/docs/current/indexes.html", k: "website", d: "intermediate", s: "B-tree, hash, GiST, GIN and BRIN — what each is for, from the source." },
      { t: "Transaction isolation levels", u: "https://www.postgresql.org/docs/current/transaction-iso.html", k: "website", d: "intermediate", s: "Read committed, repeatable read, serializable, and the anomalies each still allows." },
      { t: "A Critique of ANSI SQL Isolation Levels", u: "https://arxiv.org/abs/cs/0701157", k: "paper", d: "intermediate", s: "The paper showing the standard's isolation levels are underspecified. Still relevant." },
      { t: "PostgreSQL Exercises", u: "https://pgexercises.com/", k: "course", d: "intermediate", s: "Eighty-one graded problems against a real schema, from joins to window functions." },
      { t: "Designing Data-Intensive Applications — reading list", u: "https://github.com/ept/ddia-references", k: "code", d: "intermediate", s: "Every reference from Kleppmann's book, linked. A curriculum on its own." },
      { t: "High Scalability", u: "https://highscalability.com/", k: "website", d: "intermediate", s: "Architecture write-ups of real systems at real load, going back fifteen years." },
      { t: "Architecture of a Database System", u: "https://dsf.berkeley.edu/papers/fntdb07-architecture.pdf", k: "paper", d: "advanced", s: "Hellerstein, Stonebraker and Hamilton. The 120-page map of how a DBMS is built." },
      { t: "The Google File System", u: "https://static.googleusercontent.com/media/research.google.com/en//archive/gfs-sosp2003.pdf", k: "paper", d: "advanced", s: "The paper that started the distributed storage era, and still the clearest of them." },
      { t: "Bigtable: A Distributed Storage System", u: "https://static.googleusercontent.com/media/research.google.com/en//archive/bigtable-osdi06.pdf", k: "paper", d: "advanced", s: "The design behind almost every wide-column store that followed." },
      { t: "Dynamo: Amazon's Highly Available Key-value Store", u: "https://www.allthingsdistributed.com/files/amazon-dynamo-sosp2007.pdf", k: "paper", d: "advanced", s: "Eventual consistency argued for properly, by the people who had to live with it." },
      { t: "Spanner: Google's Globally-Distributed Database", u: "https://static.googleusercontent.com/media/research.google.com/en//archive/spanner-osdi2012.pdf", k: "paper", d: "advanced", s: "External consistency using synchronised clocks. The paper that made TrueTime famous." },
      { t: "CMU 15-721: Advanced Database Systems", u: "https://15721.courses.cs.cmu.edu/", k: "course", d: "advanced", s: "In-memory engines, vectorised execution, query compilation. The modern frontier." },
      { t: "PostgreSQL source", u: "https://github.com/postgres/postgres", k: "code", d: "advanced", s: "Thirty years of a production database, readable and heavily commented." },
    ],
  },
  {
    slug: "systems-design",
    title: "Designing systems that hold",
    topic: "systems design",
    description:
      "Scaling, failure and consistency — the tradeoffs behind a system that survives its own success.",
    items: [
      { t: "System Design Primer", u: "https://github.com/donnemartin/system-design-primer", k: "code", d: "beginner", s: "The most complete free system design resource. Start with the topic index, not the top." },
      { t: "The Twelve-Factor App", u: "https://12factor.net/", k: "website", d: "beginner", s: "Twelve constraints that make a service deployable. Short, and still correct." },
      { t: "Latency numbers every programmer should know", u: "https://gist.github.com/jboner/2841832", k: "code", d: "beginner", s: "One screen of numbers that quietly settles most architecture arguments." },
      { t: "How web caching works", u: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Caching", k: "website", d: "beginner", s: "Caching at the layer you already have, before you add one you don't." },
      { t: "Site Reliability Engineering", u: "https://sre.google/sre-book/table-of-contents/", k: "book", d: "beginner", s: "Google's SRE book, free in full. How to define reliability before you engineer it." },
      { t: "Introduction to load balancing", u: "https://www.nginx.com/resources/glossary/load-balancing/", k: "article", d: "beginner", s: "The first thing added to every growing system, explained without vendor noise." },
      { t: "Workload isolation using shuffle sharding", u: "https://aws.amazon.com/builders-library/workload-isolation-using-shuffle-sharding/", k: "article", d: "beginner", s: "One idea, explained completely: how to stop one bad tenant taking everyone down." },
      { t: "Distributed Systems lecture series", u: "https://www.youtube.com/playlist?list=PLeKd45zvjcDFUEv_ohr_HdUFe97RItdiB", k: "video", d: "intermediate", s: "Kleppmann's full Cambridge course on video, following the notes exactly." },
      { t: "Notes on Distributed Systems for Young Bloods", u: "https://www.somethingsimilar.com/2013/01/14/notes-on-distributed-systems-for-young-bloods/", k: "article", d: "intermediate", s: "Hard-won operational advice. Reads as obvious afterwards and never before." },
      { t: "Kafka: a Distributed Messaging System for Log Processing", u: "https://notes.stephenholiday.com/Kafka.pdf", k: "paper", d: "intermediate", s: "The original Kafka paper — the log as the primitive under replication and streams." },
      { t: "Jepsen: consistency models", u: "https://jepsen.io/consistency", k: "website", d: "intermediate", s: "A map of every consistency model and what each actually promises you." },
      { t: "Fallacies of distributed computing", u: "https://en.wikipedia.org/wiki/Fallacies_of_distributed_computing", k: "website", d: "intermediate", s: "Eight assumptions that are always false and always made anyway." },
      { t: "Idempotency and retries", u: "https://aws.amazon.com/builders-library/making-retries-safe-with-idempotent-APIs/", k: "article", d: "intermediate", s: "From the Amazon Builders' Library — how to retry without doing the thing twice." },
      { t: "Timeouts, retries and backoff with jitter", u: "https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/", k: "article", d: "intermediate", s: "Why naive retries turn a small outage into a large one." },
      { t: "Time, Clocks, and the Ordering of Events", u: "https://lamport.azurewebsites.net/pubs/time-clocks.pdf", k: "paper", d: "advanced", s: "Lamport, 1978. The paper that defined what 'before' means in a distributed system." },
      { t: "In Search of an Understandable Consensus Algorithm", u: "https://raft.github.io/raft.pdf", k: "paper", d: "advanced", s: "Raft. Consensus written so it can be taught, which was the entire point." },
      { t: "The Raft visualisation", u: "https://raft.github.io/", k: "website", d: "advanced", s: "Watch a cluster elect, replicate and partition. Kill a node and see what happens." },
      { t: "Harvest, Yield, and Scalable Tolerant Systems", u: "https://s3.amazonaws.com/systemsandpapers/papers/FOX_Brewer_99-Harvest_Yield_and_Scalable_Tolerant_Systems.pdf", k: "paper", d: "advanced", s: "Brewer's more useful framing of the tradeoff people usually call CAP." },
      { t: "MIT 6.824: Distributed Systems", u: "https://pdos.csail.mit.edu/6.824/", k: "course", d: "advanced", s: "Lectures, papers and labs where you implement Raft. The best course in the subject." },
      { t: "Amazon Builders' Library", u: "https://aws.amazon.com/builders-library/", k: "website", d: "advanced", s: "How Amazon actually runs things, written by the engineers who do it." },
      { t: "Jepsen analyses", u: "https://jepsen.io/analyses", k: "website", d: "advanced", s: "Databases tested to destruction, with the results published whoever they embarrass." },
    ],
  },
  {
    slug: "rust",
    title: "Learning Rust",
    topic: "rust",
    description:
      "Ownership, lifetimes and the borrow checker — the model that makes the rest of the language make sense.",
    items: [
      { t: "The Rust Programming Language", u: "https://doc.rust-lang.org/book/", k: "book", d: "beginner", s: "The book. Free, complete, and the reason Rust's learning curve is survivable." },
      { t: "Rustlings", u: "https://github.com/rust-lang/rustlings", k: "code", d: "beginner", s: "Small broken programs to fix, in order. The fastest way to get the syntax into your hands." },
      { t: "Rust by Example", u: "https://doc.rust-lang.org/rust-by-example/", k: "book", d: "beginner", s: "The same ground as the book, taught through runnable examples instead of prose." },
      { t: "Understanding Ownership", u: "https://doc.rust-lang.org/book/ch04-00-understanding-ownership.html", k: "article", d: "beginner", s: "The one chapter that decides whether the language clicks. Read it twice." },
      { t: "A Half-Hour to Learn Rust", u: "https://fasterthanli.me/articles/a-half-hour-to-learn-rust", k: "article", d: "beginner", s: "Every construct in the language, one line at a time, at speed." },
      { t: "Tour of Rust", u: "https://tourofrust.com/", k: "course", d: "beginner", s: "Side-by-side lessons with a live editor. Good if you would rather run than read." },
      { t: "The Cargo Book", u: "https://doc.rust-lang.org/cargo/", k: "book", d: "beginner", s: "The build tool and package manager, which in Rust is most of the workflow." },
      { t: "Rust for Rustaceans — chapter notes", u: "https://rust-for-rustaceans.com/", k: "website", d: "intermediate", s: "Jon Gjengset's companion material, with the free talks the book grew out of." },
      { t: "Crust of Rust", u: "https://www.youtube.com/playlist?list=PLqbS7AVVErFiWDOAVrPt7aYmnuuOLYvOa", k: "video", d: "intermediate", s: "Live streams implementing standard library pieces from scratch. Unmatched for intermediates." },
      { t: "Rust API Guidelines", u: "https://rust-lang.github.io/api-guidelines/", k: "book", d: "intermediate", s: "How to design a crate other people can use. Naming, traits, and what to make public." },
      { t: "The Rust Reference", u: "https://doc.rust-lang.org/reference/", k: "book", d: "intermediate", s: "The language defined precisely, for when the book's summary isn't enough." },
      { t: "Error handling in Rust", u: "https://doc.rust-lang.org/book/ch09-00-error-handling.html", k: "article", d: "intermediate", s: "Result, the ? operator and when panicking is the correct answer." },
      { t: "Asynchronous Programming in Rust", u: "https://rust-lang.github.io/async-book/", k: "book", d: "intermediate", s: "Futures, executors and pinning — the async model, which is unlike other languages'." },
      { t: "Learning Async Rust With Entirely Too Many Web Servers", u: "https://ibraheem.ca/posts/too-many-web-servers/", k: "article", d: "intermediate", s: "Async derived by building it, from blocking sockets up to a runtime." },
      { t: "The Rustonomicon", u: "https://doc.rust-lang.org/nomicon/", k: "book", d: "advanced", s: "Unsafe Rust, and the invariants you are promising to uphold when you use it." },
      { t: "Learn Rust With Entirely Too Many Linked Lists", u: "https://rust-unofficial.github.io/too-many-lists/", k: "book", d: "advanced", s: "Six linked lists, each failing differently. The best explanation of ownership ever written." },
      { t: "The Rust Performance Book", u: "https://nnethercote.github.io/perf-book/", k: "website", d: "advanced", s: "Profiling and the optimisations that actually pay, from a compiler engineer." },
      { t: "Rust Atomics and Locks", u: "https://marabos.nl/atomics/", k: "book", d: "advanced", s: "Mara Bos's book, free online. Concurrency primitives built up from the memory model." },
      { t: "The rustc dev guide", u: "https://rustc-dev-guide.rust-lang.org/", k: "book", d: "advanced", s: "How the compiler works, including borrow checking, written for new contributors." },
      { t: "Rust RFCs", u: "https://github.com/rust-lang/rfcs", k: "code", d: "advanced", s: "Every language decision with the argument attached. The best design record in any language." },
      { t: "The Rust standard library source", u: "https://github.com/rust-lang/rust/tree/master/library/std", k: "code", d: "advanced", s: "Idiomatic, heavily documented, and the reference for how the language is meant to be used." },
    ],
  },
];

module.exports = { CS };
